version: 2
jobs:
  python27_test: &python27_test
    docker:
    - image: docker
    environment:
      PYTHONTAG: '2.7'
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build test container
        command: docker build . --file .circleci/Dockerfile.python --build-arg PYTHONTAG=$PYTHONTAG --tag mozdata:test-py$PYTHONTAG
    - run:
        name: Dump CircleCI env vars
        command: env | grep '^CIRCLE\|CODECOV' > ci.env
    - run:
        name: Run tests
        command: docker run --rm --tty --interactive --env-file ci.env mozdata:test-py$PYTHONTAG

  python37_test:
    <<: *python27_test
    environment:
      PYTHONTAG: '3.7'

workflows:
  version: 2
  build:
    jobs:
    - python27_test
    - python37_test
